#Sat Aug 31 14:55:52 UTC 2024
micronaut:
  application.name: pattern9-async-iterate-send-tombstones
  executors:
    consumer:
      type: fixed
      nThreads: 25

kafka:
  enabled: true
  health:
    enabled: true
  bootstrap:
    servers: localhost:9092
  producers:
    state-store-cleanup-job:
      schema.registry.url: http://localhost:8081
      key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
      value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
      retries: 5
  streams:
    default:
      schema.registry.url: http://localhost:8081
      session.timeout.ms: 10000
      internal.leave.group.on.close: true
      default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      auto.offset.reset: earliest

endpoints:
  all:
    sensitive: false
